Models/EntityDataModel/SOLUTION.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raklet.Models.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLUTION
    {
        public int SOLUTION_ID { get; set; }
        public string NAME_SURENAME { get; set; }
        public string E_MAIL { get; set; }
        public string SOLUTION1 { get; set; }
        public Nullable<int> SUBID { get; set; }
    
        public virtual SUBJECT SUBJECT { get; set; }
    }
}

Controllers/SOLUTIONController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Raklet.Models.EntityDataModel;

namespace Raklet.Controllers
{
    public class SOLUTIONController : Controller
    {
        private StackOverflowEntities db = new StackOverflowEntities();

        // GET: SOLUTION
        public ActionResult Index()
        {
            var sOLUTION = db.SOLUTION.Include(s => s.SUBJECT);
            return View(sOLUTION.ToList());
        }

        // GET: SOLUTION/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOLUTION sOLUTION = db.SOLUTION.Find(id);
            if (sOLUTION == null)
            {
                return HttpNotFound();
            }
            return View(sOLUTION);
        }

        // GET: SOLUTION/Create
        public ActionResult Create()
        {
            ViewBag.SUBID = new SelectList(db.SUBJECT, "SUBJECT_ID", "PROBLEM");
            return View();
        }

        // POST: SOLUTION/Create 
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SOLUTION_ID,NAME_SURENAME,E_MAIL,SOLUTION1,SUBID")] SOLUTION sOLUTION)
        {
            if (ModelState.IsValid)
            {
                db.SOLUTION.Add(sOLUTION);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SUBID = new SelectList(db.SUBJECT, "SUBJECT_ID", "PROBLEM", sOLUTION.SUBID);
            return View(sOLUTION);
        }

        // GET: SOLUTION/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOLUTION sOLUTION = db.SOLUTION.Find(id);
            if (sOLUTION == null)
            {
                return HttpNotFound();
            }
            ViewBag.SUBID = new SelectList(db.SUBJECT, "SUBJECT_ID", "PROBLEM", sOLUTION.SUBID);
            return View(sOLUTION);
        }

        // POST: SOLUTION/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SOLUTION_ID,NAME_SURENAME,E_MAIL,SOLUTION1,SUBID")] SOLUTION sOLUTION)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sOLUTION).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SUBID = new SelectList(db.SUBJECT, "SUBJECT_ID", "PROBLEM", sOLUTION.SUBID);
            return View(sOLUTION);
        }

        // GET: SOLUTION/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOLUTION sOLUTION = db.SOLUTION.Find(id);
            if (sOLUTION == null)
            {
                return HttpNotFound();
            }
            return View(sOLUTION);
        }

        // POST: SOLUTION/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SOLUTION sOLUTION = db.SOLUTION.Find(id);
            db.SOLUTION.Remove(sOLUTION);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/SOLUTION/Create.cshtml
@model Raklet.Models.EntityDataModel.SOLUTION

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <style>
        .a {
            height: 200px;
            width: 500px;
            text-align: start;
            word-break: break-word;
            display: inline-block;
            overflow: auto;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("Create", "SOLUTION", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>SOLUTION</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label>NAME :</label> <br>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NAME_SURENAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NAME_SURENAME, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label>E-MAIL :</label> <br>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.E_MAIL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.E_MAIL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label>SOLUTION :</label> <br>
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.SOLUTION1, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.EditorFor(model => model.SOLUTION1, new { htmlAttributes = new { @class = "a"  } })
                    @Html.ValidationMessageFor(model => model.SOLUTION1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label>CHOOSE A PROBLEM :</label> <br>
                <div class="col-md-10">
                    @Html.DropDownList("SUBID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SUBID, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/SOLUTION/Delete.cshtml
@model Raklet.Models.EntityDataModel.SOLUTION

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>SOLUTION</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NAME_SURENAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NAME_SURENAME)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.E_MAIL)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.E_MAIL)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SOLUTION1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SOLUTION1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SUBJECT.PROBLEM)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SUBJECT.PROBLEM)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/SOLUTION/Details.cshtml
@model Raklet.Models.EntityDataModel.SOLUTION

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>SOLUTION</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NAME_SURENAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NAME_SURENAME)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.E_MAIL)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.E_MAIL)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SOLUTION1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SOLUTION1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SUBJECT.PROBLEM)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SUBJECT.PROBLEM)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.SOLUTION_ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/SOLUTION/Edit.cshtml
@model Raklet.Models.EntityDataModel.SOLUTION

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>SOLUTION</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.SOLUTION_ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.NAME_SURENAME, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NAME_SURENAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NAME_SURENAME, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.E_MAIL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.E_MAIL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.E_MAIL, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SOLUTION1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SOLUTION1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SOLUTION1, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SUBID, "SUBID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SUBID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SUBID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/SOLUTION/Index.cshtml
@model IEnumerable<Raklet.Models.EntityDataModel.SOLUTION>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NAME_SURENAME)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.E_MAIL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SOLUTION1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SUBJECT.PROBLEM)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NAME_SURENAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.E_MAIL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SOLUTION1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SUBJECT.PROBLEM)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.SOLUTION_ID }) |
                @Html.ActionLink("Details", "Details", new { id=item.SOLUTION_ID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.SOLUTION_ID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>