Controllers/StackOverflowController.cs
using Raklet.Models.EntityDataModel;
using Raklet.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Raklet.Controllers
{
    public class StackOverflowController : Controller
    {
        StackOverflowEntities db = new StackOverflowEntities();

        public ActionResult Index() {

            return View(db.SUBJECT.ToList());
        }
        public ActionResult Create() {


            return View();

        }
        [HttpPost]
        public ActionResult Create(string problem) {

            SUBJECT s = new SUBJECT();
            s.PROBLEM = problem;
            db.SUBJECT.Add(s);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id) {
            List<SOLUTION> value = db.SOLUTION.Where(x => x.SUBID == id).ToList();
            return View(value.ToList());
        }
        public ActionResult Search(string q)
        {
            var value = from d in db.SUBJECT select d;
            if (!string.IsNullOrEmpty("q")) {
                value = value.Where(x => x.PROBLEM.Contains(q));
            }
            return View(value.ToList());
        }

        //[HttpPost]

        //public ActionResult CreateDetail(SOLUTION solution)
        //{
        //    db.SOLUTION.Add(solution);
        //    db.SaveChanges();
        //    return RedirectToAction("Details");


        //    return View();

        //}
    }
    }

Views/StackOverflow/Create.cshtml
@model Raklet.Models.EntityDataModel.SUBJECT

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <style>
        .form-group .col-md-10 .form-control{
            
        }

    </style>
</head>
<body>
    @using (Html.BeginForm("Create","StackOverflow",FormMethod.Post)) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>SUBJECT</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.PROBLEM, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.TextAreaFor(model => model.PROBLEM, new { htmlAttributes = new { style = "height:500px" } })*@
                    <textarea class="form-control" id="TextArea" rows="20" name="PROBLEM"></textarea>
                    @Html.ValidationMessageFor(model => model.PROBLEM, "", new { @class = "text-danger" })

                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/StackOverflow/CreateDetail.cshtml
@model  Raklet.Models.EntityDataModel.SOLUTION

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateDetail</title>
</head>
<body>
    @using (Html.BeginForm("CreateDetail", "StackOverflow", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>SOLUTION</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
                @Html.LabelFor(model => model.NAME_SURENAME, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea class="form-control" id="TextArea" rows="2" name="NAME_SURENAME"></textarea>
                    @Html.ValidationMessageFor(model => model.NAME_SURENAME, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.E_MAIL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea class="form-control" id="TextArea" rows="2" name="E_MAIL"></textarea>
                    @Html.ValidationMessageFor(model => model.E_MAIL, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SOLUTION1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea class="form-control" id="TextArea" rows="2" name="SOLUTION"></textarea>
                    @Html.ValidationMessageFor(model => model.SOLUTION1, "", new { @class = "text-danger" })
                </div>
            </div>*@
    
            @*<div class="form-group">
                @Html.LabelFor(model => model.SUBID, "SUBID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SUBID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SUBID, "", new { @class = "text-danger" })
                </div>*@
          @*  *@  <!--</div>-->
            

        <div class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Add Answer</h5>    
                    </div>
                    <div class="modal-body">
                        <form method="post" action="https://localhost:44325/StackOverflow/CreateDetail" >
                            <label for="fname"> Name:</label><br>
                            <input type="text" id="fname" name="NAME_SURENAME"><br>
                            <label for="lname">E-MAIL:</label><br>
                            <input type="text" id="lname" name="E_MAIL"><br />
                            <label for="fname">SOLUTION :</label><br>
                            <input type="text" id="fname" name="SOLUTION"><br>
                        </form>
                    </div>
                    <div class="modal-footer">                     
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>


        </div>
        <div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
            </div>
    }
</body>
</html>

<script>
    $('#myModal').on('shown.bs.modal', function () {
  $('#myInput').trigger('focus')
})
</script>

Views/StackOverflow/DetailProblems.cshtml
@model IEnumerable<Raklet.Models.EntityDataModel.SOLUTION>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DetailProblems</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NAME_SURENAME)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.E_MAIL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SOLUTION1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SUBJECT.PROBLEM)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NAME_SURENAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.E_MAIL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SOLUTION1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SUBJECT.PROBLEM)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.SOLUTION_ID }) |
                @Html.ActionLink("Details", "Details", new { id=item.SOLUTION_ID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.SOLUTION_ID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

Views/StackOverflow/Details.cshtml
@model IEnumerable<Raklet.Models.EntityDataModel.SOLUTION>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DetailProblems</title>
    <style>
        
            .table,td,th

        {
            width: 1000%;
            border-collapse: collapse;
            background-color: ghostwhite;
        }
        
    </style>
</head>
<body>
    <p>
        @Html.ActionLink("Give Answer", "Create", "SOLUTION")
    </p>
    <table class="table">
        <tr>
            <th>
                <label>Answers</label>
            </th>
           
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <pre>
                    @Html.DisplayFor(modelItem => item.SOLUTION1)

</pre>

                    <p><b>Author :</b>@Html.DisplayFor(modelItem => item.NAME_SURENAME)</p>

                    <br />
                    <hr />
                </td>
                
            </tr>
            
            
        }

    </table>
    
</body>
</html>

Views/StackOverflow/Index.cshtml
@model IEnumerable<Raklet.Models.EntityDataModel.SUBJECT>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>

        #navlist {
            background-color: #0074D9;
            position: absolute;
            width: 100%;
        }

           
            #navlist a {
                float: left;
                display: flex;
                color: #f2f2f2;
                padding: 12px;
                text-decoration: none;
                font-size: 15px;
                text-align: center;
                margin-top:15px;
                background-color:darkblue;
                border-radius:5px;
                margin-left:3%;
            }

        .navlist-right {
            float: right;
        }

        
        #navlist a:hover {
            background-color: #ddd;
            color: black;
            border-radius
        }

        
        .search input[type=text] {
            width: 300px;
            height: 25px;
            border-radius: 25px;
            border: none;
        }

        .search {
            float: right;
            margin: 7px;
        }

            .search button {
                background-color: #0074D9;
                color: #f2f2f2;
                float: right;
                padding: 5px 10px;
                margin-right: 16px;
                font-size: 12px;
                border: none;
                cursor: pointer;
            }
        .subject  {
            width: 100px;
            height: 100px;
            position: absolute;
            left: 18%;
            top: 7%;
        }
        .subject .table,td,th {
            width:1000%;
            border-collapse:collapse;
            background-color:ghostwhite;  
        }
            .subject a {
                text-decoration: none;
                background-color: #0074D9;
                border-radius: 25px;
                color:white;
            }
                .subject a:hover {
                    background-color:#ddd;
                    border-radius:25px;
                }
    </style>
</head>
<body>
    <nav id="navlist">
        <div >
            <a href="/StackOverflow/Index">Home</a>
            <a href="#">About</a>

            <div class="search">
                @*<form action="@Url.Action("Search", "SOLUTION")" method="post">
                    <input type="text"
                           placeholder=" Search"
                           name="search">
                    <button>
                        <i class="fa fa-search"
                           style="font-size: 18px;">
                        </i>
                    </button>
                </form>*@
                @using (Html.BeginForm("Search", "StackOverflow", FormMethod.Get)) {
                <p>
                    @Html.TextBox("q")
                    <input type="submit" value="Search" />
                </p>
                
                }
            </div>
        </div>
    </nav>
    
    <div class="subject">
        <br>
        <br />
        <p>
            <a class="NameStyle" href="/StackOverflow/Create">Create Problem</a>
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PROBLEM)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PROBLEM)

                        <br />
                        <br />
                        <hr />
                    </td>
                    <td>

                        @Html.ActionLink("Details", "Details", new { id = item.SUBJECT_ID })
                        <br />
                        <br />
                       

                    </td>
                </tr>
            }

        </table>
    </div>
</body>
</html>

Views/StackOverflow/Search.cshtml
@model IEnumerable<Raklet.Models.EntityDataModel.SUBJECT>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>

        #navlist {
            background-color: #0074D9;
            position: absolute;
            width: 100%;
        }

            
            #navlist a {
                float: left;
                display: flex;
                color: #f2f2f2;
                padding: 12px;
                text-decoration: none;
                font-size: 15px;
                text-align: center;
                margin-top: 15px;
                background-color: darkblue;
                border-radius: 5px;
                margin-left: 3%;
            }

        .navlist-right {
            float: right;
        }

        
        #navlist a:hover {
            background-color: #ddd;
            color: black;
            border-radius
        }

        
        .search input[type=text] {
            width: 300px;
            height: 25px;
            border-radius: 25px;
            border: none;
        }

        .search {
            float: right;
            margin: 7px;
        }

            .search button {
                background-color: #0074D9;
                color: #f2f2f2;
                float: right;
                padding: 5px 10px;
                margin-right: 16px;
                font-size: 12px;
                border: none;
                cursor: pointer;
            }

        .subject {
            width: 100px;
            height: 100px;
            position: absolute;
            left: 18%;
            top: 7%;
        }

            .subject .table, td, th {
                width: 1000%;
                border-collapse: collapse;
                background-color: ghostwhite;
            }

            .subject a {
                text-decoration: none;
                background-color: #0074D9;
                border-radius: 25px;
                color: white;
            }

                .subject a:hover {
                    background-color: #ddd;
                    border-radius: 25px;
                }
    </style>
</head>

@*<div class="container body-content">
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - n</p>
            </footer>
        </div>
    </body>*@
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <nav>
        <div id="navlist">
            <a href="https://localhost:44325/StackOverflow/Index">Home</a>
            <a href="#">About</a>

            <div class="search">
                @*<form action="@Url.Action("Search", "SOLUTION")" method="post">
                        <input type="text"
                               placeholder=" Search"
                               name="search">
                        <button>
                            <i class="fa fa-search"
                               style="font-size: 18px;">
                            </i>
                        </button>
                    </form>*@
                @using (Html.BeginForm("Search", "StackOverflow", FormMethod.Get))
                {
                    <p> Search : @Html.TextBox("q")</p>
                    <input type="submit" value="Search" />

                }
            </div>
        </div>
    </nav>
    <div class="subject">
        <br>
        <p>
            <a class="NameStyle" href="https://localhost:44325/StackOverflow/Create">Create Problem</a>
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PROBLEM)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PROBLEM)
                    </td>
                    <td>

                        @Html.ActionLink("Details", "Details", new { id = item.SUBJECT_ID })

                    </td>
                </tr>
            }

        </table>
    </div>
</body>
</html>